config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :competences, only: [:index]
  resources :realisations, only: [:index]
  resources :equipes, only: [:index]
  resources :reviews, only: [:index]
  resources :contacts, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["www.planty-secrets.site"] || "localhost:3000" }
  end
end

app/controllers/competences_controller.rb
class CompetencesController < ApplicationController

  def show
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def show
  end
end

app/controllers/equipes_controller.rb
class EquipesController < ApplicationController

  def show
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/realisations_controller.rb
class RealisationsController < ApplicationController
  def show
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competences_helper.rb
module CompetencesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/realisations_helper.rb
module RealisationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/competences/index.html.erb
<div class="container">
  <div class="cards-competences">
    <div class="card-product-left">
      <%= image_tag "pierre.jpg", alt: "maçonnerie de pierre" %>
      <div class="card-product-infos">
        <h3>MACONNERIE DE PIERRE</h3>
        <p>Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.</p>
      </div>
    </div>
    <div class="card-product-right">
      <div class="card-product-infos">
        <h3>OUVERTURE DE MURS PORTEURS</h3>
        <p>Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.</p>
      </div>
      <a href="" data-toggle="popover" data-img="http://placehold.it/400x200" title="Popover Header" ></a>
      <%= image_tag "pierre.jpg", alt: "maçonnerie de pierre" %>
    </div>
    <div class="card-product-left">
      <%= image_tag "pierre.jpg", alt: "maçonnerie de pierre" %>
      <div class="card-product-infos">
        <h3>REJOINTOIEMENT</h3>
        <p>Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.</p>
      </div>
    </div>
    <div class="card-product-right">
      <div class="card-product-infos">
        <h3>AGRANDISSEMENT</h3>
        <p>Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.</p>
      </div>
      <%= image_tag "pierre.jpg", alt: "maçonnerie de pierre" %>
    </div>
    <div class="card-product-left">
      <%= image_tag "pierre.jpg", alt: "maçonnerie de pierre" %>
      <div class="card-product-infos">
        <h3>GARAGE/TERRASSE</h3>
        <p>Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.</p>
      </div>
    </div>
    <div class="card-product-right">
      <div class="card-product-infos">
        <h3>MUR/MURET</h3>
        <p>Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.Lorem ipsum dolor sit amet consectetur. Consectetur eget auctor maecenas felis tempus.</p>
      </div>
      <%= image_tag "pierre.jpg", alt: "maçonnerie de pierre" %>
    </div>
  </div>

  <div class="linksyellow">
    <strong><%= link_to "Retour accueil", root_path, class:"btnyellow" %></strong>
  </div>

</div>

app/views/contacts/index.html.erb
<section class="contact section" id="contact">
  <h1 class="section__title">Contactez-nous pour toutes demandes concernant vos projets !</h1>

  <div class="contact__container container grid" data-controller="contacts">
    <form action="" class="contact__form" id="contact-form" data-contacts-target="form" >
      <div class="contact__group">
        <input type="text" name="user_name" required placeholder="Entrez votre nom" class="contact__input">
        <input type="email" name="user_email" required placeholder="Entrez votre email" class="contact__input">
      </div>

      <textarea name="user_project" require placeholder="Entrez votre message" class="contact__input"></textarea>

      <p class="contact__message" id="contact-message" data-contacts-target="messalert"></p>

      <button type="submit" class="btnyellow contact__button" data-action="submit->contacts#sendEmail">Envoyer</button>
    </form>
  </div>

</section>

<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js"></script>

app/views/equipes/index.html.erb
<h1 class= "team-title">Notre équipe au service de vos projets</h1>

<div class="team">
  <div class="card-member">
    <%= image_tag "ex-photo.jpg", alt:"photo d'un membre de l'équipe", class: "photo-member"%>
    <div class="member-text">
    <p>Prénom/Nom</p>
    </div>
  </div>

  <div class="card-member">
    <%= image_tag "ex-photo.jpg", alt:"photo d'un membre de l'équipe", class: "photo-member"%>
    <div class="member-text">
    <p>Prénom/Nom</p>
    </div>
  </div>

  <div class="card-member">
    <%= image_tag "ex-photo.jpg", alt:"photo d'un membre de l'équipe", class: "photo-member"%>
    <div class="member-text">
    <p>Prénom/Nom</p>
    </div>
  </div>

  <div class="card-member">
    <%= image_tag "ex-photo.jpg", alt:"photo d'un membre de l'équipe", class: "photo-member"%>
    <div class="member-text">
    <p>Prénom/Nom</p>
    </div>
  </div>
</div>

<div class="photo-presentation">
  <%= image_tag "camion.jpg", alt: "camion société", class: "camion" %>
  <%= image_tag "camion.jpg", alt: "camion société", class: "camion" %>
</div>

  <div class="linksyellow">
    <strong><%= link_to "Retour accueil", root_path, class:"btnyellow" %></strong>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ML Maconnerie - Neuf & Rénovations</title>
    <meta name="description" content="Découvrez les compétences et réalisations de ML Maçonnerie, spécialisée en neuf et rénovations. Notre équipe est à votre disposition pour tous vos projets de construction." />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <div class="main-container">
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="main">
    <%= image_tag "wallpaper.jpg", class:"wallpaper", alt:"collage de photos" %>
    <div class="header">
      <h1 class="ml">ML Maçonnerie</h1>
      <h2>Neuf & Rénovations</h2>
    </div>
  </div>
  <div  class="subtitle">
    <p>Des services de qualité pour vos projets de maçonnerie neufs et de rénovation.</p>
  </div>
  <div class="linksyellow">
    <strong><%= link_to "Nos Compétences", competences_path, class:"btnyellow" %></strong>
    <strong><%= link_to "Nos Réalisations", realisations_path, class:"btnyellow" %></strong>
    <strong><%= link_to "Notre Equipe", equipes_path, class:"btnyellow" %></strong>
    <strong><%= link_to "Avis Clients", reviews_path, class:"btnyellow" %></strong>
  </div>
</div>

app/views/realisations/index.html.erb
  <div class="cards">
    <div class="card-project">
        <%= image_tag "facade.jpg", class:"project-img" %>
        <div class="texte">
          <h4><strong>Maçonnerie de pierre</strong></h4>
          <p>test<br>
          <strong class="strong">test</strong></p>
        </div>
    </div>

    <div class="card-project">
      <%= image_tag "pierre.jpg", class:"project-img" %>
      <div class="texte">
        <h4><strong>Ouverture de murs porteurs</strong></h4>
        <p>test<br>
        <strong class="strong">test</strong></p>
      </div>
    </div>

    <div class="card-project">
      <%= image_tag "reno.jpg", class:"project-img" %>
      <div class="texte">
        <h4><strong>Rejointement</strong></h4>
        <p>test<br>
        <strong class="strong">test</strong></p>
      </div>
    </div>

    <div class="card-project">
      <%= image_tag "facade.jpg", class:"project-img" %>
      <div class="texte">
        <h4><strong>Agrandissement</strong></h4>
        <p>test<br>
        <strong class="strong">test</strong></p>
      </div>
    </div>

    <div class="card-project">
      <%= image_tag "pierre.jpg", class:"project-img" %>
      <div class="texte">
        <h4><strong>Garage/Terrasse</strong></h4>
        <p>test<br>
        <strong class="strong">test</strong></p>
      </div>
    </div>

    <div class="card-project">
      <%= image_tag "reno.jpg", class:"project-img" %>
      <div class="texte">
        <h4><strong>Mur/Murets</strong></h4>
        <p>test<br>
        <strong class="strong">test</strong></p>
      </div>
    </div>

    <div class="linksyellow">
      <strong><%= link_to "Accueil", root_path, class:"btnyellow" %></strong>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span> Opération effectuée avec succès </span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <span> Une erreur s'est produite </span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="d-flex align-items-center">
    <i class="fa-solid fa-trowel-bricks me-3 fa-xl brickicon" style="color: #eeff00;"></i>
    <p class="address"><strong>ML Maçonnerie <br>Sainte-Marie <br>44260 MALVILLE</strong></p>
  </div>
  <div class="footer-links">
    <a href="https://www.facebook.com/ml.maconnerie.5" target="_blank"><i class="fa-brands fa-square-facebook" style="color: #fbff00;"></i></a>
  </div>
  <%= link_to "Mentions Légales", root_path, class:"linksmentions" %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar-mlmaconnerie">
  <%= image_tag "logo.jpg", alt:"logo", class:"logo" %>

  <div class="navbarcontainer">
    <div class="contactinfos">
      <div class="d-flex mt-4 me-4">
        <i class="fa-solid fa-phone me-2"></i>
        <p><strong>06.88.76.14.30</strong></p>
      </div>
      <div class="d-flex mt-4 me-5">
        <i class="fa-solid fa-envelopes-bulk me-2"></i>
        <p><strong>mlmaconnerie@laposte.net</strong></p>
      </div>
    </div>

    <div class="dropdown">
      <button class="dropbtn"><i class="fa-solid fa-bars fa-xl mt-3" style="color: #fbff00;"></i></i>
      </button>
      <div class="dropdown-content">
        <a href="/#">Accueil</a>
        <a href="/competences">Nos Compétences</a>
        <a href="/realisations">Nos Réalisations</a>
        <a href="/equipes">Notre Equipe</a>
        <a href="/reviews">Avis Clients</a>
        <a href="/contacts">Contactez-nous</a>
      </div>
    </div>

  </div>
</nav>